/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 19 21:37:29 GMT 2017
 */

package evosuite;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import models.EContinente;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EContinente_ESTest extends EContinente_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 3 covered goals:
   * Goal 1. [Output]: models.EContinente.values()[Lmodels/EContinente;:NonEmptyArray
   * Goal 2. [METHOD] models.EContinente.values()[Lmodels/EContinente;
   * Goal 3. [METHODNOEX] models.EContinente.values()[Lmodels/EContinente;
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EContinente[] eContinenteArray0 = EContinente.values();
      assertNotNull(eContinenteArray0);
  }

  //Test case number: 1
  /*
   * 3 covered goals:
   * Goal 1. [Output]: models.EContinente.valueOf(Ljava/lang/String;)Lmodels/EContinente;:NonNull:models.EContinente:ordinal()I:Zero
   * Goal 2. [METHOD] models.EContinente.valueOf(Ljava/lang/String;)Lmodels/EContinente;
   * Goal 3. [METHODNOEX] models.EContinente.valueOf(Ljava/lang/String;)Lmodels/EContinente;
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EContinente eContinente0 = EContinente.valueOf("AFRICA");
      assertEquals("\u00C1frica", eContinente0.getContinente());
  }

  //Test case number: 2
  /*
   * 3 covered goals:
   * Goal 1. [Output]: models.EContinente.valueOf(Ljava/lang/String;)Lmodels/EContinente;:NonNull:models.EContinente:ordinal()I:Positive
   * Goal 2. [METHOD] models.EContinente.valueOf(Ljava/lang/String;)Lmodels/EContinente;
   * Goal 3. [METHODNOEX] models.EContinente.valueOf(Ljava/lang/String;)Lmodels/EContinente;
   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EContinente eContinente0 = EContinente.valueOf("AMERICA_DO_NORTE");
      assertEquals("Am\u00E9rica do Norte", eContinente0.getContinente());
  }

  //Test case number: 3
  /*
   * 29 covered goals:
   * Goal 1. models.EContinente.getContinente()Ljava/lang/String;: root-Branch
   * Goal 2. models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: I12 Branch 1 IF_ICMPGE L23 - false
   * Goal 3. models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: I23 Branch 2 IFLE L24 - true
   * Goal 4. models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: I23 Branch 2 IFLE L24 - false
   * Goal 5. Branch models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: I12 Branch 1 IF_ICMPGE L23 - false in context: models.EContinente:getEnum(Ljava/lang/String;)Lmodels/EContinente;
   * Goal 6. Branch models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: I23 Branch 2 IFLE L24 - false in context: models.EContinente:getEnum(Ljava/lang/String;)Lmodels/EContinente;
   * Goal 7. Branch models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: I23 Branch 2 IFLE L24 - true in context: models.EContinente:getEnum(Ljava/lang/String;)Lmodels/EContinente;
   * Goal 8. [Output]: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:NonNull:models.EContinente:ordinal()I:Positive
   * Goal 9. models.EContinente.getContinente()Ljava/lang/String;: Line 19
   * Goal 10. models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: Line 23
   * Goal 11. models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: Line 24
   * Goal 12. models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: Line 25
   * Goal 13. [METHOD] models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;
   * Goal 14. [METHODNOEX] models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;
   * Goal 15. Weak Mutation 0: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:23 - ReplaceConstant - 0 -> 1
   * Goal 16. Weak Mutation 1: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:23 - ReplaceComparisonOperator >= -> -1
   * Goal 17. Weak Mutation 4: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:24 - ReplaceVariable eContinente -> AMERICA_LATINA
   * Goal 18. Weak Mutation 5: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:24 - ReplaceVariable eContinente -> AFRICA
   * Goal 19. Weak Mutation 6: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:24 - ReplaceVariable eContinente -> AMERICA_DO_NORTE
   * Goal 20. Weak Mutation 7: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:24 - ReplaceVariable eContinente -> ASIA
   * Goal 21. Weak Mutation 8: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:24 - ReplaceVariable eContinente -> OCEANIA
   * Goal 22. Weak Mutation 9: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:24 - ReplaceVariable eContinente -> EUROPA
   * Goal 23. Weak Mutation 10: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:24 - ReplaceComparisonOperator <= -> -1
   * Goal 24. Weak Mutation 11: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:24 - ReplaceComparisonOperator <= -> ==
   * Goal 25. Weak Mutation 13: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:25 - ReplaceVariable eContinente -> AMERICA_LATINA
   * Goal 26. Weak Mutation 14: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:25 - ReplaceVariable eContinente -> AFRICA
   * Goal 27. Weak Mutation 15: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:25 - ReplaceVariable eContinente -> AMERICA_DO_NORTE
   * Goal 28. Weak Mutation 16: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:25 - ReplaceVariable eContinente -> ASIA
   * Goal 29. Weak Mutation 17: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:25 - ReplaceVariable eContinente -> OCEANIA
   */

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      EContinente eContinente0 = EContinente.getEnum("Europa");
      assertEquals("Europa", eContinente0.getContinente());
  }

  //Test case number: 4
  /*
   * 2 covered goals:
   * Goal 1. valueOf(Ljava/lang/String;)Lmodels/EContinente;_java.lang.NullPointerException_IMPLICIT
   * Goal 2. [METHOD] models.EContinente.valueOf(Ljava/lang/String;)Lmodels/EContinente;
   */

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try { 
        EContinente.valueOf((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Name is null
         //
         assertThrownBy("java.lang.Enum", e);
      }
  }

  //Test case number: 5
  /*
   * 2 covered goals:
   * Goal 1. valueOf(Ljava/lang/String;)Lmodels/EContinente;_java.lang.IllegalArgumentException_IMPLICIT
   * Goal 2. [METHOD] models.EContinente.valueOf(Ljava/lang/String;)Lmodels/EContinente;
   */

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      // Undeclared exception!
      try { 
        EContinente.valueOf("w&wqtS$Zc4kO0`g");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant models.EContinente.w&wqtS$Zc4kO0`g
         //
         assertThrownBy("java.lang.Enum", e);
      }
  }

  //Test case number: 6
  /*
   * 25 covered goals:
   * Goal 1. models.EContinente.getContinente()Ljava/lang/String;: root-Branch
   * Goal 2. models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: I12 Branch 1 IF_ICMPGE L23 - false
   * Goal 3. models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: I23 Branch 2 IFLE L24 - false
   * Goal 4. Branch models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: I12 Branch 1 IF_ICMPGE L23 - false in context: models.EContinente:getEnum(Ljava/lang/String;)Lmodels/EContinente;
   * Goal 5. Branch models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: I23 Branch 2 IFLE L24 - false in context: models.EContinente:getEnum(Ljava/lang/String;)Lmodels/EContinente;
   * Goal 6. [Output]: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:NonNull:models.EContinente:ordinal()I:Zero
   * Goal 7. models.EContinente.getContinente()Ljava/lang/String;: Line 19
   * Goal 8. models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: Line 23
   * Goal 9. models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: Line 24
   * Goal 10. models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: Line 25
   * Goal 11. [METHOD] models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;
   * Goal 12. [METHODNOEX] models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;
   * Goal 13. Weak Mutation 0: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:23 - ReplaceConstant - 0 -> 1
   * Goal 14. Weak Mutation 1: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:23 - ReplaceComparisonOperator >= -> -1
   * Goal 15. Weak Mutation 4: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:24 - ReplaceVariable eContinente -> AMERICA_LATINA
   * Goal 16. Weak Mutation 6: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:24 - ReplaceVariable eContinente -> AMERICA_DO_NORTE
   * Goal 17. Weak Mutation 7: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:24 - ReplaceVariable eContinente -> ASIA
   * Goal 18. Weak Mutation 8: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:24 - ReplaceVariable eContinente -> OCEANIA
   * Goal 19. Weak Mutation 9: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:24 - ReplaceVariable eContinente -> EUROPA
   * Goal 20. Weak Mutation 10: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:24 - ReplaceComparisonOperator <= -> -1
   * Goal 21. Weak Mutation 13: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:25 - ReplaceVariable eContinente -> AMERICA_LATINA
   * Goal 22. Weak Mutation 15: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:25 - ReplaceVariable eContinente -> AMERICA_DO_NORTE
   * Goal 23. Weak Mutation 16: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:25 - ReplaceVariable eContinente -> ASIA
   * Goal 24. Weak Mutation 17: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:25 - ReplaceVariable eContinente -> OCEANIA
   * Goal 25. Weak Mutation 18: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:25 - ReplaceVariable eContinente -> EUROPA
   */

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      EContinente eContinente0 = EContinente.getEnum("\u00C1frica");
      assertEquals("AFRICA", eContinente0.name());
  }

  //Test case number: 7
  /*
   * 24 covered goals:
   * Goal 1. models.EContinente.getContinente()Ljava/lang/String;: root-Branch
   * Goal 2. models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: I12 Branch 1 IF_ICMPGE L23 - true
   * Goal 3. models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: I12 Branch 1 IF_ICMPGE L23 - false
   * Goal 4. models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: I23 Branch 2 IFLE L24 - true
   * Goal 5. Branch models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: I12 Branch 1 IF_ICMPGE L23 - true in context: models.EContinente:getEnum(Ljava/lang/String;)Lmodels/EContinente;
   * Goal 6. Branch models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: I12 Branch 1 IF_ICMPGE L23 - false in context: models.EContinente:getEnum(Ljava/lang/String;)Lmodels/EContinente;
   * Goal 7. Branch models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: I23 Branch 2 IFLE L24 - true in context: models.EContinente:getEnum(Ljava/lang/String;)Lmodels/EContinente;
   * Goal 8. [Output]: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:Null
   * Goal 9. models.EContinente.getContinente()Ljava/lang/String;: Line 19
   * Goal 10. models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: Line 23
   * Goal 11. models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: Line 24
   * Goal 12. models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;: Line 28
   * Goal 13. [METHOD] models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;
   * Goal 14. [METHODNOEX] models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;
   * Goal 15. Weak Mutation 0: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:23 - ReplaceConstant - 0 -> 1
   * Goal 16. Weak Mutation 1: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:23 - ReplaceComparisonOperator >= -> -1
   * Goal 17. Weak Mutation 2: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:23 - ReplaceComparisonOperator >= -> >
   * Goal 18. Weak Mutation 4: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:24 - ReplaceVariable eContinente -> AMERICA_LATINA
   * Goal 19. Weak Mutation 5: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:24 - ReplaceVariable eContinente -> AFRICA
   * Goal 20. Weak Mutation 6: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:24 - ReplaceVariable eContinente -> AMERICA_DO_NORTE
   * Goal 21. Weak Mutation 7: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:24 - ReplaceVariable eContinente -> ASIA
   * Goal 22. Weak Mutation 8: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:24 - ReplaceVariable eContinente -> OCEANIA
   * Goal 23. Weak Mutation 9: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:24 - ReplaceVariable eContinente -> EUROPA
   * Goal 24. Weak Mutation 11: models.EContinente.getEnum(Ljava/lang/String;)Lmodels/EContinente;:24 - ReplaceComparisonOperator <= -> ==
   */

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      EContinente.getEnum("\u00C1sja");
  }

  //Test case number: 8
  /*
   * 6 covered goals:
   * Goal 1. models.EContinente.getContinente()Ljava/lang/String;: root-Branch
   * Goal 2. Branch models.EContinente.getContinente()Ljava/lang/String;: root-Branch in context: models.EContinente:getContinente()Ljava/lang/String;
   * Goal 3. [Output]: models.EContinente.getContinente()Ljava/lang/String;:NonEmptyString
   * Goal 4. models.EContinente.getContinente()Ljava/lang/String;: Line 19
   * Goal 5. [METHOD] models.EContinente.getContinente()Ljava/lang/String;
   * Goal 6. [METHODNOEX] models.EContinente.getContinente()Ljava/lang/String;
   */

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      EContinente eContinente0 = EContinente.AFRICA;
      String string0 = eContinente0.getContinente();
      assertEquals("\u00C1frica", string0);
  }
}
